### PR TITLE
adds initial support for message selectors

### LINKED ISSUE #69: Add message selector support for queues and topics
At the moment, there is no possibility to set message selectors for queues and topics.
This enhancement should be added.

### PR DESCRIPTION
**Pull request by grimmjo**
Hi,
this was just a try to add support for message selectors.. I haven't tested it yet. The changes are straight forward.

closes #69

### CODE REVIEW

**Comment by elliottpope** [comment]
Thanks for the contribution @grimmjo. I'll take a look at it over the course of the week and add comments

**Comment by elliottpope** [comment]
Hey @grimmjo, could you take a look at the tests in the `docs-examples` directory and write a test to cover the addition of message selectors?

**Comment by graemerocher** [comment]
@grimmjo any update on @elliottpope comments?

**Comment by grimmjo** [comment]
@graemerocher I totally forgot this PR. Sorry...
I'm going to rebase this PR and provide the missing tests tomorrow.

**Comment by grimmjo** [comment]
@graemerocher and @elliottpope: Rebased, tests added and docs written 😃

**Pull request merged**
