### PR TITLE
Use new JsonMapper abstraction for serde compatibility

### PR DESCRIPTION
**Pull request by yawkat**
No version bump because this is pending a major release anyway.

The build is a bit weird, I wasn't able to apply the new build plugin pattern from the other projects. Not sure why.

### CODE REVIEW

**Comment by ilopmar** [comment]
> The build is a bit weird, I wasn't able to apply the new build plugin pattern from the other projects. Not sure why.

probably because the build is too old. Maybe you can ping @melix so he can help you upgrade the build too.

**Review by ilopmar — DISMISSED** [review]

**Comment by yawkat** [comment]
Native image tests are failing too. Maybe because of the test upgrade.

**Comment by graemerocher** [comment]
to fix the native tests we need to bump to the latest version of `micronaut-test`

**Comment by graemerocher** [comment]
ie `3.0.4` of `micronaut-test`

Maybe you want to try that?

**Comment by yawkat** [comment]
ah didnt know there was 3.0.4. that fixes the tests at least.

**Pull request merged**
